on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: recap
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix profile install .#release-env
      - uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        id: semanticrelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        with:
          semantic_version: ^25.0.0
          extra_plugins: |
            @semantic-release/git@^10
            @semantic-release/changelog@^6
            @semantic-release/exec@^7
            conventional-changelog-conventionalcommits@^8
            @cihelper/semanticrelease-plugin-uv@^1
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        if: ${{ steps.semanticrelease.outputs.new_release_published == 'true' }}
