on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: cachix/cachix-action@v16
        with:
          name: recap
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix profile install .#release-env
      - uses: cycjimmy/semantic-release-action@v4
        id: semanticrelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        with:
          semantic_version: ^24
          extra_plugins: |
            @semantic-release/git@^10
            @semantic-release/changelog@^6
            @semantic-release/exec@^7
            conventional-changelog-conventionalcommits@^8
            @cihelper/semanticrelease-plugin-uv@^1
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.new_release_published == 'true' }}
