on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v5
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix profile install .#releaseEnv
      - uses: cycjimmy/semantic-release-action@v3
        id: semanticrelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: ^19
          extra_plugins: |
            @semantic-release/git@^10
            @semantic-release/changelog@^6
            @semantic-release/exec@^6
            conventional-changelog-conventionalcommits@^5
            @cihelper/semanticrelease-plugin-poetry@^1
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.new_release_published == 'true' }}
