on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix profile install .#releaseEnv
      - uses: cycjimmy/semantic-release-action@v4
        id: semanticrelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        with:
          semantic_version: ^23
          extra_plugins: |
            @semantic-release/git@^10
            @semantic-release/changelog@^6
            @semantic-release/exec@^6
            conventional-changelog-conventionalcommits@^7
            @cihelper/semanticrelease-plugin-poetry@^2
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.new_release_published == 'true' }}
